/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp statusarea.xml -a inputmethodstatusindicatoradaptor -c InputMethodStatusIndicatorAdaptor -l InputMethodStatusIndicator -i statusindicator.h
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef INPUTMETHODSTATUSINDICATORADAPTOR_H_1273065987
#define INPUTMETHODSTATUSINDICATORADAPTOR_H_1273065987

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "statusindicator.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.meego.core.MInputMethodStatusIndicator
 */
class InputMethodStatusIndicatorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.meego.core.MInputMethodStatusIndicator")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.meego.core.MInputMethodStatusIndicator\">\n"
"    <method name=\"setIconID\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"iconID\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    InputMethodStatusIndicatorAdaptor(InputMethodStatusIndicator *parent);
    virtual ~InputMethodStatusIndicatorAdaptor();

    inline InputMethodStatusIndicator *parent() const
    { return static_cast<InputMethodStatusIndicator *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void setIconID(const QString &iconID);
Q_SIGNALS: // SIGNALS
};

#endif
