/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp statusarea.xml -a inputmethodstatusindicatoradaptor -c InputMethodStatusIndicatorAdaptor -l InputMethodStatusIndicator -i statusindicator.h
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "inputmethodstatusindicatoradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class InputMethodStatusIndicatorAdaptor
 */

InputMethodStatusIndicatorAdaptor::InputMethodStatusIndicatorAdaptor(InputMethodStatusIndicator *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

InputMethodStatusIndicatorAdaptor::~InputMethodStatusIndicatorAdaptor()
{
    // destructor
}

void InputMethodStatusIndicatorAdaptor::setIconID(const QString &iconID)
{
    // handle method call com.meego.core.MInputMethodStatusIndicator.setIconID
    parent()->setIconID(iconID);
}

