/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp statusarearenderer.xml -a statusarearendereradaptor -c StatusAreaRendererAdaptor -l StatusAreaRenderer -i statusarearenderer.h
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef STATUSAREARENDERERADAPTOR_H_1277934288
#define STATUSAREARENDERERADAPTOR_H_1277934288

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "statusarearenderer.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.meego.core.MStatusBar
 */
class StatusAreaRendererAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.meego.core.MStatusBar")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.meego.core.MStatusBar\">\n"
"    <method name=\"sharedPixmapHandle\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"handle\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    StatusAreaRendererAdaptor(StatusAreaRenderer *parent);
    virtual ~StatusAreaRendererAdaptor();

    inline StatusAreaRenderer *parent() const
    { return static_cast<StatusAreaRenderer *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    uint sharedPixmapHandle();
Q_SIGNALS: // SIGNALS
};

#endif
