/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbusinterfacenotificationsink.xml -a dbusinterfacenotificationsinkadaptor -c DBusInterfaceNotificationSinkAdaptor -l DBusInterfaceNotificationSink -i dbusinterfacenotificationsink.h -i metatypedeclarations.h
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusinterfacenotificationsinkadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusInterfaceNotificationSinkAdaptor
 */

DBusInterfaceNotificationSinkAdaptor::DBusInterfaceNotificationSinkAdaptor(DBusInterfaceNotificationSink *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusInterfaceNotificationSinkAdaptor::~DBusInterfaceNotificationSinkAdaptor()
{
    // destructor
}

void DBusInterfaceNotificationSinkAdaptor::registerSink(const QString &service, const QString &path)
{
    // handle method call com.meego.core.MNotificationManager.registerSink
    parent()->registerSink(service, path);
}

void DBusInterfaceNotificationSinkAdaptor::unregisterSink(const QString &service, const QString &path)
{
    // handle method call com.meego.core.MNotificationManager.unregisterSink
    parent()->unregisterSink(service, path);
}

