/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp ../../libnotificationsystem/notificationsink.xml -p dbusinterfacenotificationsinkproxy -c DBusInterfaceNotificationSinkProxy -i metatypedeclarations.h
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSINTERFACENOTIFICATIONSINKPROXY_H_1284454200
#define DBUSINTERFACENOTIFICATIONSINKPROXY_H_1284454200

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "metatypedeclarations.h"

/*
 * Proxy class for interface com.meego.core.MNotificationSink
 */
class DBusInterfaceNotificationSinkProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.meego.core.MNotificationSink"; }

public:
    DBusInterfaceNotificationSinkProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DBusInterfaceNotificationSinkProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> addGroup(uint groupId, NotificationParameters parameters)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(groupId) << qVariantFromValue(parameters);
        return asyncCallWithArgumentList(QLatin1String("addGroup"), argumentList);
    }

    inline QDBusPendingReply<> addNotification(Notification notification)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(notification);
        return asyncCallWithArgumentList(QLatin1String("addNotification"), argumentList);
    }

    inline QDBusPendingReply<> removeGroup(uint groupId)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(groupId);
        return asyncCallWithArgumentList(QLatin1String("removeGroup"), argumentList);
    }

    inline QDBusPendingReply<> removeNotification(uint notificationId)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(notificationId);
        return asyncCallWithArgumentList(QLatin1String("removeNotification"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void notificationGroupClearingRequested(uint groupId);
    void notificationRemovalRequested(uint notificationId);
};

namespace com {
  namespace meego {
    namespace core {
      typedef ::DBusInterfaceNotificationSinkProxy MNotificationSink;
    }
  }
}
#endif
